
version: "branch-{branch}-build-nr-{build}"
skip_tags: true

build: off

install:
  - echo %PATH%
  - appveyor DownloadFile https://winampplugins.co.uk/curl/curl_7_53_1_openssl_nghttp2_x64.7z -FileName curl.7z
  - dir
  - curl --version
