
language: nix
script: nix-build default.nix

before_install:
  - >
      if ! echo "$TRAVIS_COMMIT_MESSAGE" \
         | grep -E  '\[(skip travis|travis skip)\]'
      then
        echo "[skip travis] has been found, exiting."
        exit
      fi

      if ! git diff --name-only $TRAVIS_COMMIT_RANGE \
         | grep -qvE '\.md$'
      then
        echo "Only docs were updated, stopping build process."
        exit
      fi
